# Generated by Django 4.1.5 on 2023-02-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tweet",
            name="coment_of",
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="likes_count",
        ),
        migrations.AddField(
            model_name="tweet",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
